### ISSUE TITLE
github action support

### ISSUE THREAD

**Issue by SteffenSeckler** [TUM-LIS/tum-dissertation-latex#18]
Hi,

maybe it would be helpful for some people to document, how this code could be used with github actions:

```yml
name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    # The checked-out repository is by default mounted as working directory.
    - name: Build
      uses: docker://andrerichter/tum-dissertation-latex
      with:
        entrypoint: make
        args: pdf-local
    # if your makefile is not in the root directory of your github repository, you can specify the path using make's -C argument:
    # args: -C PATH-TO-MAKEFILE-DIRECTORY pdf-local

    # Publish the artifacts, can be downloaded as zip.
    - name: Publish artifact
      uses: actions/upload-artifact@v1
      with:
        name: dissertation
        path: dissertation.pdf
```
